apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: cicd
  labels:
    app: hello-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: ghcr.io/kiril-lilac/devops-cicd-lab:sha-9f98dd7
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP_VERSION
              value: "2.0"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: cicd
spec:
  selector:
    app: hello-app
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
